Raise minimum tested toolchain to rust 1.38
Required by the transitive dev-dependency (via rayon) on crossbeam-utils.

    error[E0277]: the trait bound `atomic::seq_lock::SeqLock: std::marker::Copy` is not satisfied
       --> github.com-1ecc6299db9ec823/crossbeam-utils-0.8.11/src/atomic/atomic_cell.rs:905:36
        |
    905 |     static LOCKS: [SeqLock; LEN] = [L; LEN];
        |                                    ^^^^^^^^ the trait `std::marker::Copy` is not implemented for `atomic::seq_lock::SeqLock`
        |
        = note: the `Copy` trait is required because the repeated element will be copied

    error[E0658]: use of unstable library feature 'ptr_cast'
       --> github.com-1ecc6299db9ec823/crossbeam-utils-0.8.11/src/atomic/atomic_cell.rs:183:26
        |
    183 |         self.value.get().cast::<T>()
        |                          ^^^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/60602

    error[E0658]: use of unstable library feature 'ptr_cast'
        --> github.com-1ecc6299db9ec823/crossbeam-utils-0.8.11/src/atomic/atomic_cell.rs:1008:50
         |
    1008 |                 let val = ptr::read_volatile(src.cast::<MaybeUninit<T>>());
         |                                                  ^^^^
         |
         = note: for more information, see https://github.com/rust-lang/rust/issues/60602

    error[E0658]: use of unstable library feature 'ptr_cast'
       --> github.com-1ecc6299db9ec823/crossbeam-utils-0.8.11/src/sync/parker.rs:267:35
        |
    267 |         Arc::into_raw(this.inner).cast::<()>()
        |                                   ^^^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/60602

    error[E0658]: use of unstable library feature 'ptr_cast'
       --> github.com-1ecc6299db9ec823/crossbeam-utils-0.8.11/src/sync/parker.rs:289:38
        |
    289 |             inner: Arc::from_raw(ptr.cast::<Inner>()),
        |                                      ^^^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/60602