Raise minimum tested compiler to rust 1.80
Required by rayon.

    error: rustc 1.79.0 is not supported by the following packages:
      rayon@1.11.0 requires rustc 1.80
      rayon-core@1.13.0 requires rustc 1.80
      rayon-core@1.13.0 requires rustc 1.80
      rayon-core@1.13.0 requires rustc 1.80
    Either upgrade rustc or select compatible dependency versions with
    `cargo update <name>@<current-ver> --precise <compatible-ver>`
    where `<compatible-ver>` is the latest version supporting rustc 1.79.0