Raise minimum tested compiler to 1.63
Required by the newest release of rayon.

    error: package `rayon-core v1.12.0` cannot be built because it
    requires rustc 1.63 or newer, while the currently active rustc
    version is 1.59.0