Raise minimum tested rustc to 1.59
Required by the example code's dependency on rayon.

    $ cargo +1.56.0 run --example readme
    error: package `rayon-core v1.11.0` cannot be built because it
    requires rustc 1.59 or newer, while the currently active rustc
    version is 1.56.0